SELECT * FROM Espacios;
INSERT INTO Espacios(nombre, tipo, ubicacion)
VALUES 
	('Salon 100-NP', 'salon', 'Primer piso, nuevo pabellon'), 
    ('Salon 101-NP', 'salon', 'Primer piso, nuevo pabellon'), 
    ('Salon 102-NP', 'salon', 'Primer piso, nuevo pabellon'), 
    ('Salon 103-NP', 'salon', 'Primer piso, nuevo pabellon'), 
    ('Salon 104-NP', 'salon', 'Primer piso, nuevo pabellon'), 
    ('Salon 105-NP', 'salon', 'Primer piso, nuevo pabellon'), 
    ('Salon 106-NP', 'salon', 'Primer piso, nuevo pabellon'), 
    ('Salon 107-NP', 'salon', 'Primer piso, nuevo pabellon'), 
    ('Salon 108-NP', 'salon', 'Primer piso, nuevo pabellon'), 
    ('Salon 109-NP', 'salon', 'Primer piso, nuevo pabellon'), 
    
    ('Salon 200-NP', 'salon', 'Segundo piso, nuevo pabellon'), 
    ('Salon 201-NP', 'salon', 'Segundo piso, nuevo pabellon'), 
    ('Salon 202-NP', 'salon', 'Segundo piso, nuevo pabellon'), 
    
    ('Salon 100-AP', 'salon', 'Primer piso, antiguo pabellon'), 
    ('Salon 101-AP', 'salon', 'Primer piso, antiguo pabellon'), 
    ('Salon 102-AP', 'salon', 'Primer piso, antiguo pabellon'), 
    ('Salon 103-AP', 'salon', 'Primer piso, antiguo pabellon'), 
    ('Salon 104-AP', 'salon', 'Primer piso, antiguo pabellon'), 
    ('Salon 105-AP', 'salon', 'Primer piso, antiguo pabellon'), 
    ('Salon 106-AP', 'salon', 'Primer piso, antiguo pabellon'), 
    ('Salon 107-AP', 'salon', 'Primer piso, antiguo pabellon'), 
    ('Salon 108-AP', 'salon', 'Primer piso, antiguo pabellon'), 
    ('Salon 109-AP', 'salon', 'Primer piso, antiguo pabellon'), 
    
    ('Salon 200-AP', 'salon', 'Segundo piso, antiguo pabellon'), 
    ('Salon 201-AP', 'salon', 'Segundo piso, antiguo pabellon'), 
    ('Salon 202-AP', 'salon', 'Segundo piso, antiguo pabellon'), 
    ('Salon 203-AP', 'salon', 'Segundo piso, antiguo pabellon'), 
    ('Salon 204-AP', 'salon', 'Segundo piso, antiguo pabellon'), 
    ('Salon 206-AP', 'salon', 'Segundo piso, antiguo pabellon'), 
    ('Salon 207-AP', 'salon', 'Segundo piso, antiguo pabellon'), 
    ('Salon 208-AP', 'salon', 'Segundo piso, antiguo pabellon'), 
    ('Salon 209-AP', 'salon', 'Segundo piso, antiguo pabellon'), 
    ('Salon 210-AP', 'salon', 'Segundo piso, antiguo pabellon'),
	
    ('Salon 300-AP', 'salon', 'Tercer piso, antiguo pabellon'), 
    ('Salon 301-AP', 'salon', 'Tercer piso, antiguo pabellon'),
    ('Salon 302-AP', 'salon', 'Tercer piso, antiguo pabellon'),
    ('Salon 303-AP', 'salon', 'Tercer piso, antiguo pabellon'), 
    ('Salon 304-AP', 'salon', 'Tercer piso, antiguo pabellon'),
    ('Salon 305-AP', 'salon', 'Tercer piso, antiguo pabellon'),
    ('Salon 306-AP', 'salon', 'Tercer piso, antiguo pabellon'),
    ('Salon 307-AP', 'salon', 'Tercer piso, antiguo pabellon'),
    ('Salon 308-AP', 'salon', 'Tercer piso, antiguo pabellon'),
    ('Salon 309-AP', 'salon', 'Tercer piso, antiguo pabellon'),
    ('Salon 310-AP', 'salon', 'Tercer piso, antiguo pabellon'),
    ('Salon 311-AP', 'salon', 'Tercer piso, antiguo pabellon'),
	('Salon 312-AP', 'salon', 'Tercer piso, antiguo pabellon'),
    
    ('Laboratorio primer nivel', 'laboratorio', 'Primer piso, antiguo pabellon'), 
    ('Laboratorio 01', 'laboratorio', 'Segundo piso, nuevo pabellon'), 
    ('Laboratorio 02', 'laboratorio', 'Segundo piso, nuevo pabellon'), 
    ('Laboratorio 03', 'laboratorio', 'Segundo piso, nuevo pabellon'), 
    ('laboratorio 04', 'laboratorio', 'Segundo piso, nuevo pabellon'), 
    ('Laboratorio 05', 'laboratorio', 'Segundo piso, nuevo pabellon'),
    ('Laboratorio 06', 'laboratorio', 'Segundo piso, nuevo pabellon'), 
    ('Laboratorio 02', 'laboratorio', 'Tercer piso, nuevo pabellon'), 
    ('Laboratorio 03', 'laboratorio', 'Tercer piso, nuevo pabellon'), 
    ('laboratorio 04', 'laboratorio', 'Tercer piso, nuevo pabellon'), 
    ('Laboratorio 06', 'laboratorio', 'Tercer piso, nuevo pabellon'), 
    ('Laboratorio 07', 'laboratorio', 'Tercer piso, nuevo pabellon'),
    ('Laboratorio 08', 'laboratorio', 'Tercer piso, nuevo pabellon'),
    
    ('Aula Magna', 'salon', 'Segundo piso, antiguo pabellon'),
    ('Salon de musica', 'salon','Tercer piso, nuevo pabellon'),
    ('Salon de estudio', 'laboratorio','Primer piso, nuevo pabellon'),
    ('Salon de estudio', 'laboratorio','Segundo piso, nuevo pabellon');
    